.ORIG x3000
LEA R0, AUX
.STRINGZ "abcdacsdacasdcasdcasdcsadcsadcsadcsdacsadcsadcsadcsadcasdsadasdasdasdabcdacsdacasdcasdcasdcsadcsadcsadcsdacsadcsadcsadcsadcasdsadasdasdasdabcdacsdacasdcasdcasdcsadcsadcsadcsdacsadcsadcsadcsadcasdsadasdasdasdabcdacsdacasdcasdcasdcsadcsadcsadcsdacsadcsadcsadcsadcasdsadasdasdasdabcdacsdacasdcasdcasdcsadcsadcsadcsdacsadcsadcsadcsadcasdsadasdasdasdabcdacsdacasdcasdcasdcsadcsadcsadcsdacsadcsadcsadcsadcasdsadasdasdasdabcdacsdacasdcasdcasdcsadcsadcsadcsdacsadcsadcsadcsadcasdsadasdasdasdabcdacsdacasdcasdcasdcsadcsadcsadcsdacsadcsadcsadcsadcasdsadasdasdasdabcdacsdacasdcasdcasdcsadcsadcsadcsdacsadcsadcsadcsadcasdsadasdasdasdabcdacsdacasdcasdcasdcsadcsadcsadcsdacsadcsadcsadcsadcasdsadasdasdasdabcdacsdacasdcasdcasdcsadcsadcsadcsdacsadcsadcsadcsadcasdsadasdasdasdabcdacsdacasdcasdcasdcsadcsadcsadcsdacsadcsadcsadcsadcasdsadasdasdasdabcdacsdacasdcasdcasdcsadcsadcsadcsdacsadcsadcsadcsadcasdsadasdasdasd"
AUX .FILL x0000
ENDADDRESS .END
